databases:
  - name: db
    plan: free
    databaseName: b4gfbkv1vywowjbkflbg
    user: u94c1gtx0rfgtr8gunoa

services:
  - type: web
    plan: free
    name: inventario
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn inventario.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: b4gfbkv1vywowjbkflbg
          property: postgresql://u94c1gtx0rfgtr8gunoa:KaARvHEllD2TzSMfopDI6uqHwOkfQw@b4gfbkv1vywowjbkflbg-postgresql.services.clever-cloud.com:50013/b4gfbkv1vywowjbkflbg
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4