databases:
  - name: db
    plan: free
    databaseName: inventario
    user: admin

services:
  - type: web
    plan: free
    name: inventario
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn inventario.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4