# Generated by Django 3.2.3 on 2022-06-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F2MCompany',
            fields=[
                ('ciacod', models.AutoField(db_column='CiaCod', primary_key=True, serialize=False)),
                ('cianom', models.CharField(db_column='CiaNom', max_length=60)),
                ('ciaruc', models.BigIntegerField(db_column='CiaRUC')),
                ('ciacap', models.DecimalField(db_column='CiaCap', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'f2m_compañia',
            },
        ),
        migrations.CreateModel(
            name='GzzEstadoRegistro',
            fields=[
                ('estregcod', models.CharField(db_column='EstRegCod', max_length=1, primary_key=True, serialize=False)),
                ('estregdes', models.CharField(db_column='EstRegDes', max_length=40)),
                ('estregestreg', models.ForeignKey(db_column='EstRegEstReg', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'gzz_estado_registro',
            },
        ),
        migrations.CreateModel(
            name='GzzSino',
            fields=[
                ('tiposncod', models.AutoField(db_column='TipOsnCod', primary_key=True, serialize=False)),
                ('tiposndes', models.CharField(db_column='TipOsnDes', max_length=40)),
                ('tiposnestreg', models.ForeignKey(db_column='TipOsnEstReg', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'gzz_sino',
            },
        ),
        migrations.CreateModel(
            name='R1MTrabajador',
            fields=[
                ('trbcod', models.AutoField(db_column='TrbCod', primary_key=True, serialize=False)),
                ('trbnom', models.CharField(db_column='TrbNom', max_length=60)),
                ('trbcon', models.CharField(db_column='TrbCon', max_length=10)),
                ('trartt', models.ForeignKey(db_column='TraRtt', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzsino')),
                ('trbciacod', models.ForeignKey(db_column='TrbCiaCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.f2mcompany')),
                ('trbestreg', models.ForeignKey(db_column='TrbEstReg', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'r1m_trabajador',
                'unique_together': {('trbcod', 'trbciacod')},
            },
        ),
        migrations.CreateModel(
            name='V2MCliente',
            fields=[
                ('clicod', models.AutoField(db_column='CliCod', primary_key=True, serialize=False)),
                ('clinom', models.CharField(db_column='CliNom', max_length=60)),
                ('clidni', models.IntegerField(blank=True, db_column='CliDNI', null=True)),
                ('cliestregcod', models.ForeignKey(db_column='CliEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'v2m_cliente',
            },
        ),
        migrations.CreateModel(
            name='V1TTransaccion',
            fields=[
                ('tracod', models.AutoField(db_column='TraCod', primary_key=True, serialize=False)),
                ('tranom', models.CharField(db_column='TraNom', max_length=60)),
                ('tradsc', models.CharField(db_column='TraDsc', max_length=250)),
                ('trapre', models.DecimalField(db_column='TraPre', decimal_places=2, max_digits=5)),
                ('traestregcod', models.ForeignKey(db_column='TraEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'v1t_transaccion',
            },
        ),
        migrations.CreateModel(
            name='V1TBoletaEleCab',
            fields=[
                ('bolelecabcod', models.AutoField(db_column='BolEleCabCod', primary_key=True, serialize=False)),
                ('bolelecabfecdia', models.IntegerField(db_column='BolEleCabFecDia')),
                ('bolelecabfecmes', models.IntegerField(db_column='BolEleCabFecMes')),
                ('bolelecabfecaño', models.IntegerField(db_column='BolEleCabFecAño')),
                ('bolelecabhor', models.IntegerField(db_column='BolEleCabHor')),
                ('bolelecabmin', models.IntegerField(db_column='BolEleCabMin')),
                ('bolelecabseg', models.IntegerField(db_column='BolEleCabSeg')),
                ('bolelecabtot', models.IntegerField(db_column='BolEleCabTot')),
                ('bolelecabclicod', models.ForeignKey(db_column='BolEleCabCliCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.v2mcliente')),
                ('bolelecabestregcod', models.ForeignKey(db_column='BolEleCabEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
                ('bolelecabtrbcod', models.ForeignKey(db_column='BolEleCabTrbCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.r1mtrabajador')),
            ],
            options={
                'db_table': 'v1t_boleta_ele_cab',
            },
        ),
        migrations.CreateModel(
            name='L1MArticulo',
            fields=[
                ('artcod', models.AutoField(db_column='ArtCod', primary_key=True, serialize=False)),
                ('artcodbar', models.IntegerField(db_column='ArtCodBar')),
                ('artnom', models.CharField(db_column='ArtNom', max_length=60)),
                ('artdsc', models.CharField(db_column='ArtDsc', max_length=250)),
                ('artpreuni', models.DecimalField(db_column='ArtPreUni', decimal_places=2, max_digits=6)),
                ('artstk', models.IntegerField(db_column='ArtStk')),
                ('artestregcod', models.ForeignKey(db_column='ArtEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'l1m_articulo',
                'unique_together': {('artcod', 'artcodbar')},
            },
        ),
        migrations.CreateModel(
            name='F2TPagos',
            fields=[
                ('pagcod', models.AutoField(db_column='PagCod', primary_key=True, serialize=False)),
                ('pagnom', models.CharField(db_column='PagNom', max_length=60)),
                ('pagdsc', models.CharField(db_column='PagDsc', max_length=250)),
                ('pagpre', models.DecimalField(db_column='PagPre', decimal_places=2, max_digits=6)),
                ('pagfecaño', models.IntegerField(db_column='PagFecAño')),
                ('pagfecmes', models.IntegerField(db_column='PagFecMes')),
                ('pagfecdia', models.IntegerField(db_column='PagFecDia')),
                ('paghor', models.IntegerField(db_column='PagHor')),
                ('pagmin', models.IntegerField(db_column='PagMin')),
                ('pagseg', models.IntegerField(db_column='PagSeg')),
                ('pagestregcod', models.ForeignKey(db_column='PagEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
                ('pagtrbcod', models.ForeignKey(db_column='PagTrbCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.r1mtrabajador')),
            ],
            options={
                'db_table': 'f2t_pagos',
            },
        ),
        migrations.AddField(
            model_name='f2mcompany',
            name='ciaestregcod',
            field=models.ForeignKey(db_column='CiaEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.CreateModel(
            name='F2HControlVen',
            fields=[
                ('convencod', models.AutoField(db_column='ConVenCod', primary_key=True, serialize=False)),
                ('convencapfin', models.DecimalField(db_column='ConVenCapFin', decimal_places=2, max_digits=10)),
                ('convenbolelecabcod', models.ForeignKey(blank=True, db_column='ConVenBolEleCabCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.v1tboletaelecab')),
                ('convenciacod', models.ForeignKey(db_column='ConVenCiaCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.f2mcompany')),
                ('convenestregcod', models.ForeignKey(db_column='ConVenEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
                ('convenpagcod', models.ForeignKey(blank=True, db_column='ConVenPagCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.f2tpagos')),
            ],
            options={
                'db_table': 'f2h_control_ven',
            },
        ),
        migrations.CreateModel(
            name='V1TBoletaEleDetTra',
            fields=[
                ('boleledettrabolelecabcod', models.OneToOneField(db_column='BolEleDetTraBolEleCabCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventarioTienda.v1tboletaelecab')),
                ('boleledettratracan', models.IntegerField(db_column='BolEleDetTraTraCan')),
                ('boleledettratraimp', models.DecimalField(db_column='BolEleDetTraTraImp', decimal_places=2, max_digits=5)),
                ('boleledettraestregcod', models.ForeignKey(db_column='BolEleDetTraEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
                ('boleledettratracod', models.ForeignKey(db_column='BolEleDetTraTraCod', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.v1ttransaccion')),
            ],
            options={
                'db_table': 'v1t_boleta_ele_det_tra',
                'unique_together': {('boleledettrabolelecabcod', 'boleledettratracod')},
            },
        ),
        migrations.CreateModel(
            name='V1TBoletaEleDetArt',
            fields=[
                ('boleledetartbolelecabcod', models.OneToOneField(db_column='BolEleDetArtBolEleCabCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventarioTienda.v1tboletaelecab')),
                ('boleledetartartcan', models.IntegerField(db_column='BolEleDetArtArtCan')),
                ('boleledetartartimp', models.DecimalField(db_column='BolEleDetArtArtImp', decimal_places=2, max_digits=5)),
                ('boleledetartartcod', models.ForeignKey(db_column='BolEleDetArtArtCod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artCod', to='inventarioTienda.l1marticulo')),
                ('boleledetartartcodbar', models.ForeignKey(db_column='BolEleDetArtArtCodBar', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artCodBar', to='inventarioTienda.l1marticulo')),
                ('boleledetartestreg', models.ForeignKey(db_column='BolEleDetArtEstReg', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'v1t_boleta_ele_det_art',
                'unique_together': {('boleledetartbolelecabcod', 'boleledetartartcod', 'boleledetartartcodbar')},
            },
        ),
    ]
