# Generated by Django 3.2.3 on 2022-06-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0002_remove_gzzestadoregistro_estregestreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gzzestadoregistro',
            name='estregestreg',
            field=models.ForeignKey(db_column='EstRegEstReg', default='A', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.gzzestadoregistro'),
        ),
    ]
