# Generated by Django 3.2.3 on 2022-06-12 23:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0003_gzzestadoregistro_estregestreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2mcompany',
            name='ciaruc',
            field=models.BigIntegerField(db_column='CiaRUC', max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecaño',
            field=models.IntegerField(db_column='PagFecAño', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecdia',
            field=models.IntegerField(db_column='PagFecDia', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecmes',
            field=models.IntegerField(db_column='PagFecMes', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='paghor',
            field=models.IntegerField(db_column='PagHor', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagmin',
            field=models.IntegerField(db_column='PagMin', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagseg',
            field=models.IntegerField(db_column='PagSeg', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artcodbar',
            field=models.IntegerField(db_column='ArtCodBar', max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artstk',
            field=models.IntegerField(db_column='ArtStk', max_length=3),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecaño',
            field=models.IntegerField(db_column='BolEleCabFecAño', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecdia',
            field=models.IntegerField(db_column='BolEleCabFecDia', max_length=4, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecmes',
            field=models.IntegerField(db_column='BolEleCabFecMes', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabhor',
            field=models.IntegerField(db_column='BolEleCabHor', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabmin',
            field=models.IntegerField(db_column='BolEleCabMin', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabseg',
            field=models.IntegerField(db_column='BolEleCabSeg', max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcan',
            field=models.IntegerField(db_column='BolEleDetArtArtCan', max_length=3),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcodbar',
            field=models.ForeignKey(db_column='BolEleDetArtArtCodBar', on_delete=django.db.models.deletion.DO_NOTHING, to='inventarioTienda.l1marticulo'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettratracan',
            field=models.IntegerField(db_column='BolEleDetTraTraCan', max_length=3),
        ),
        migrations.AlterField(
            model_name='v2mcliente',
            name='clidni',
            field=models.IntegerField(blank=True, db_column='CliDNI', max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledetart',
            unique_together={('boleledetartbolelecabcod', 'boleledetartartcodbar')},
        ),
        migrations.RemoveField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcod',
        ),
    ]
