# Generated by Django 3.2.3 on 2022-06-13 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0004_auto_20220612_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2mcompany',
            name='ciaruc',
            field=models.BigIntegerField(db_column='CiaRUC', validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecaño',
            field=models.IntegerField(db_column='PagFecAño', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2090)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecdia',
            field=models.IntegerField(db_column='PagFecDia', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagfecmes',
            field=models.IntegerField(db_column='PagFecMes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='paghor',
            field=models.IntegerField(db_column='PagHor', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagmin',
            field=models.IntegerField(db_column='PagMin', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagseg',
            field=models.IntegerField(db_column='PagSeg', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artcodbar',
            field=models.IntegerField(db_column='ArtCodBar', validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artstk',
            field=models.IntegerField(db_column='ArtStk', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecaño',
            field=models.IntegerField(db_column='BolEleCabFecAño', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2090)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecdia',
            field=models.IntegerField(db_column='BolEleCabFecDia', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabfecmes',
            field=models.IntegerField(db_column='BolEleCabFecMes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabhor',
            field=models.IntegerField(db_column='BolEleCabHor', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabmin',
            field=models.IntegerField(db_column='BolEleCabMin', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabseg',
            field=models.IntegerField(db_column='BolEleCabSeg', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabtot',
            field=models.DecimalField(db_column='BolEleCabTot', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcan',
            field=models.IntegerField(db_column='BolEleDetArtArtCan', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettratracan',
            field=models.IntegerField(db_column='BolEleDetTraTraCan', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='v2mcliente',
            name='clidni',
            field=models.IntegerField(blank=True, db_column='CliDNI', null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
