# Generated by Django 3.2.3 on 2022-06-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0005_auto_20220612_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f2hcontrolven',
            name='convenbolelecabcod',
        ),
        migrations.RemoveField(
            model_name='f2hcontrolven',
            name='convenpagcod',
        ),
        migrations.AddField(
            model_name='f2tpagos',
            name='pagconvencod',
            field=models.ForeignKey(blank=True, db_column='PagConVenCod', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2hcontrolven'),
        ),
        migrations.AddField(
            model_name='v1tboletaelecab',
            name='bolelecabconvencod',
            field=models.ForeignKey(blank=True, db_column='BolEleCabConVenCod', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2hcontrolven'),
        ),
        migrations.AlterField(
            model_name='f2hcontrolven',
            name='convenciacod',
            field=models.ForeignKey(db_column='ConVenCiaCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2mcompany'),
        ),
        migrations.AlterField(
            model_name='f2hcontrolven',
            name='convenestregcod',
            field=models.ForeignKey(db_column='ConVenEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='f2mcompany',
            name='ciaestregcod',
            field=models.ForeignKey(db_column='CiaEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagestregcod',
            field=models.ForeignKey(db_column='PagEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagtrbcod',
            field=models.ForeignKey(db_column='PagTrbCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.r1mtrabajador'),
        ),
        migrations.AlterField(
            model_name='gzzestadoregistro',
            name='estregestreg',
            field=models.ForeignKey(db_column='EstRegEstReg', default='A', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='gzzsino',
            name='tiposnestreg',
            field=models.ForeignKey(db_column='TipOsnEstReg', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artestregcod',
            field=models.ForeignKey(db_column='ArtEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='r1mtrabajador',
            name='trartt',
            field=models.ForeignKey(db_column='TraRtt', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzsino'),
        ),
        migrations.AlterField(
            model_name='r1mtrabajador',
            name='trbciacod',
            field=models.ForeignKey(db_column='TrbCiaCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2mcompany'),
        ),
        migrations.AlterField(
            model_name='r1mtrabajador',
            name='trbestreg',
            field=models.ForeignKey(db_column='TrbEstReg', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabclicod',
            field=models.ForeignKey(db_column='BolEleCabCliCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.v2mcliente'),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabestregcod',
            field=models.ForeignKey(db_column='BolEleCabEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabtrbcod',
            field=models.ForeignKey(db_column='BolEleCabTrbCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.r1mtrabajador'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcodbar',
            field=models.ForeignKey(db_column='BolEleDetArtArtCodBar', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.l1marticulo'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartbolelecabcod',
            field=models.OneToOneField(db_column='BolEleDetArtBolEleCabCod', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='inventarioTienda.v1tboletaelecab'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartestreg',
            field=models.ForeignKey(db_column='BolEleDetArtEstReg', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettrabolelecabcod',
            field=models.OneToOneField(db_column='BolEleDetTraBolEleCabCod', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='inventarioTienda.v1tboletaelecab'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettraestregcod',
            field=models.ForeignKey(db_column='BolEleDetTraEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettratracod',
            field=models.ForeignKey(db_column='BolEleDetTraTraCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.v1ttransaccion'),
        ),
        migrations.AlterField(
            model_name='v1ttransaccion',
            name='traestregcod',
            field=models.ForeignKey(db_column='TraEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterField(
            model_name='v2mcliente',
            name='cliestregcod',
            field=models.ForeignKey(db_column='CliEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro'),
        ),
        migrations.AlterUniqueTogether(
            name='f2tpagos',
            unique_together={('pagcod', 'pagconvencod')},
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaelecab',
            unique_together={('bolelecabcod', 'bolelecabconvencod')},
        ),
    ]
