# Generated by Django 3.2.3 on 2022-06-13 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0006_auto_20220612_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='f2hcontrolven',
            name='convenfecaño',
            field=models.IntegerField(blank=True, db_column='ConVenFecAño', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2090)]),
        ),
        migrations.AddField(
            model_name='f2hcontrolven',
            name='convenfecdia',
            field=models.IntegerField(blank=True, db_column='ConVenFecDia', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='f2hcontrolven',
            name='convenfecmes',
            field=models.IntegerField(blank=True, db_column='ConVenFecMes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
