# Generated by Django 3.2.3 on 2022-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0007_auto_20220612_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='f2hcontrolven',
            name='convencapini',
            field=models.DecimalField(db_column='ConVenCapIni', decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
