# Generated by Django 3.2.3 on 2022-06-14 05:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0008_f2hcontrolven_convencapini'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='f2tpagos',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagconvencod',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagfecaño',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagfecdia',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagfecmes',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='paghor',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagmin',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagseg',
        ),
        migrations.RemoveField(
            model_name='f2tpagos',
            name='pagtrbcod',
        ),
        migrations.CreateModel(
            name='F2TPagosControlVen',
            fields=[
                ('pagconvenpagcod', models.OneToOneField(db_column='PagConVenPagCod', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='inventarioTienda.f2tpagos')),
                ('pagconvenfecaño', models.IntegerField(db_column='PagFecAño', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2090)])),
                ('pagconvenfecmes', models.IntegerField(db_column='PagFecMes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pagconvenfecdia', models.IntegerField(db_column='PagFecDia', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('pagconvenhor', models.IntegerField(db_column='PagHor', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('pagconvenmin', models.IntegerField(db_column='PagMin', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('pagconvenseg', models.IntegerField(db_column='PagSeg', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('pagconvenconvencod', models.ForeignKey(blank=True, db_column='PagConVenConVenCod', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2hcontrolven')),
                ('pagconvenestregcod', models.ForeignKey(db_column='PagEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro')),
                ('pagconventrbcod', models.ForeignKey(db_column='PagTrbCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.r1mtrabajador')),
            ],
            options={
                'db_table': 'f2t_pagos_con_ven',
                'unique_together': {('pagconvenpagcod', 'pagconvenconvencod')},
            },
        ),
    ]
