# Generated by Django 3.2.3 on 2022-06-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0009_auto_20220614_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2tpagoscontrolven',
            name='pagconvenconvencod',
            field=models.OneToOneField(db_column='PagConVenConVenCod', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='inventarioTienda.f2hcontrolven'),
        ),
        migrations.AlterField(
            model_name='f2tpagoscontrolven',
            name='pagconvenpagcod',
            field=models.ForeignKey(blank=True, db_column='PagConVenPagCod', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2tpagos'),
        ),
    ]
