# Generated by Django 3.2.3 on 2022-06-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0011_alter_f2tpagoscontrolven_pagconvenpagcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2tpagoscontrolven',
            name='pagconvenpagcod',
            field=models.ForeignKey(blank=True, db_column='PagConVenPagCod', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2tpagos'),
        ),
    ]
