# Generated by Django 3.2.3 on 2022-06-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0012_alter_f2tpagoscontrolven_pagconvenpagcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2tpagoscontrolven',
            name='pagconvenconvencod',
            field=models.ForeignKey(db_column='PagConVenConVenCod', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='inventarioTienda.f2hcontrolven'),
        ),
    ]
