# Generated by Django 3.2.3 on 2022-06-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0015_alter_l1marticulo_artcodbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartbolelecabcod',
            field=models.OneToOneField(db_column='BolEleDetArtBolEleCabCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inventarioTienda.v1tboletaelecab'),
        ),
    ]
