# Generated by Django 3.2.3 on 2022-06-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0016_alter_v1tboletaeledetart_boleledetartbolelecabcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1tboletaeledetart',
            name='boleledetartcod',
            field=models.AutoField(db_column='BolDetArtCod', default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='v1tboletaeledettra',
            name='boletadettracod',
            field=models.AutoField(db_column='BolDetTraCod', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartbolelecabcod',
            field=models.ForeignKey(db_column='BolEleDetArtBolEleCabCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.v1tboletaelecab'),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettrabolelecabcod',
            field=models.ForeignKey(db_column='BolEleDetTraBolEleCabCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.v1tboletaelecab'),
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledetart',
            unique_together={('boleledetartcod', 'boleledetartbolelecabcod', 'boleledetartartcodbar')},
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledettra',
            unique_together={('boletadettracod', 'boleledettrabolelecabcod', 'boleledettratracod')},
        ),
    ]
