# Generated by Django 3.2.3 on 2022-06-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0017_auto_20220617_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabtot',
            field=models.DecimalField(db_column='BolEleCabTot', decimal_places=2, max_digits=10),
        ),
    ]
