# Generated by Django 3.2.3 on 2022-06-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0018_alter_v1tboletaelecab_bolelecabtot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1ttransaccion',
            name='trapre',
            field=models.DecimalField(db_column='TraPre', decimal_places=2, max_digits=7),
        ),
    ]
