# Generated by Django 3.2.3 on 2022-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0019_alter_v1ttransaccion_trapre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2hcontrolven',
            name='convencapfin',
            field=models.DecimalField(db_column='ConVenCapFin', decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='f2hcontrolven',
            name='convencapini',
            field=models.DecimalField(db_column='ConVenCapIni', decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='f2mcompany',
            name='ciacap',
            field=models.DecimalField(db_column='CiaCap', decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='f2tpagos',
            name='pagpre',
            field=models.DecimalField(db_column='PagPre', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='l1marticulo',
            name='artpreuni',
            field=models.DecimalField(db_column='ArtPreUni', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='v1tboletaelecab',
            name='bolelecabtot',
            field=models.DecimalField(db_column='BolEleCabTot', decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartimp',
            field=models.DecimalField(db_column='BolEleDetArtArtImp', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettratraimp',
            field=models.DecimalField(db_column='BolEleDetTraTraImp', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='v1ttransaccion',
            name='trapre',
            field=models.DecimalField(db_column='TraPre', decimal_places=2, max_digits=10),
        ),
    ]
