# Generated by Django 3.2.3 on 2022-06-21 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0020_auto_20220620_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1marticulo',
            name='artcodbar',
            field=models.IntegerField(db_column='ArtCodBar', validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterUniqueTogether(
            name='l1marticulo',
            unique_together=set(),
        ),
    ]
