# Generated by Django 3.2.3 on 2022-06-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0021_auto_20220621_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1tboletaeledetart',
            name='boleledetartartcan',
            field=models.DecimalField(db_column='BolEleDetArtArtCan', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='v1tboletaeledettra',
            name='boleledettratracan',
            field=models.DecimalField(db_column='BolEleDetTraTraCan', decimal_places=2, max_digits=10),
        ),
    ]
