# Generated by Django 3.2.3 on 2022-06-25 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0022_auto_20220621_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1marticulo',
            name='artcodbar',
            field=models.IntegerField(db_column='ArtCodBar', default=0, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
