# Generated by Django 3.2.3 on 2022-09-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0023_alter_l1marticulo_artcodbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='F2MAlmacen',
            fields=[
                ('alncod', models.AutoField(db_column='almcod', primary_key=True, serialize=False)),
                ('alndsc', models.CharField(db_column='CiaNom', max_length=360)),
                ('alnestregcod', models.ForeignKey(db_column='CiaEstRegCod', on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.gzzestadoregistro')),
            ],
            options={
                'db_table': 'f2m_almacen',
            },
        ),
        migrations.AddField(
            model_name='l1marticulo',
            name='artaln',
            field=models.ForeignKey(blank=True, db_column='ArtAln', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventarioTienda.f2malmacen'),
        ),
    ]
