# Generated by Django 3.2.3 on 2022-09-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarioTienda', '0024_auto_20220901_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='r1mtrabajador',
            name='trausr',
            field=models.ForeignKey(blank=True, db_column='TrbUsr', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
