# Generated by Django 3.2.3 on 2023-01-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0025_r1mtrabajador_trausr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r1mtrabajador',
            name='trartt',
        ),
    ]
