# Generated by Django 3.2.3 on 2023-02-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0026_remove_r1mtrabajador_trartt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='f2tpagoscontrolven',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='r1mtrabajador',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaelecab',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledetart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledettra',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='f2mcompany',
            table='f2m_company',
        ),
    ]
