# Generated by Django 3.2.3 on 2023-02-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0028_alter_r1mtrabajador_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='v1tboletaeledettra',
            unique_together={('boletadettracod', 'boleledettrabolelecabcod', 'boleledettratracod')},
        ),
    ]
