# Generated by Django 3.2.3 on 2023-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0029_alter_v1tboletaeledettra_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1tboletaeledettra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=555, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='v1tboletaeledettra',
            unique_together={('boleledettrabolelecabcod', 'boleledettratracod')},
        ),
        migrations.RemoveField(
            model_name='v1tboletaeledettra',
            name='boletadettracod',
        ),
    ]
