# Generated by Django 3.2.3 on 2023-02-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTienda', '0030_auto_20230131_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='f2tpagoscontrolven',
            name='id',
            field=models.BigAutoField(auto_created=True, default=555, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='f2tpagoscontrolven',
            unique_together={('pagconvenconvencod',)},
        ),
        migrations.RemoveField(
            model_name='f2tpagoscontrolven',
            name='pagconvencod',
        ),
    ]
